### ISSUE TITLE
Smaller collapsed states of entities for a better overview of the roster

### ISSUE THREAD

**Issue by mr-frog** [RosterizerTestData/Warhammer40k10e#17] opened 2023-06-19 14:42 UTC
To be able to easier navigate the units i already added to my roster i would love it if they collapsed even further when not highlighted.
For example for the Blade Champion here it would be helpful if he only showed up as "Blade Champion" in the most collapsed state not showing any weapon or enhancement choices.
![image](https://github.com/RosterizerTestData/Warhammer40k10e/assets/55178725/636ddaa5-e985-42f9-91d1-d80cbb8ecff7)

**Comment by ThePants999** [comment] 2023-06-20 08:54
Hmmm. We'll need to chat about that one - the inventory view and the card view have different purposes, so it's a little unfortunate if they follow the same logic for what they display.

**Comment by TheGameKnave** [comment] 2023-06-20 08:58
> Hmmm. We'll need to chat about that one - the inventory view and the card view have different purposes, so it's a little unfortunate if they follow the same logic for what they display.

The unfortunatest part is that the inventory nav ***IS*** a copy of the card view, with most of the visibility turned off. :) That nav should really be its own thing; you're right. A refactor has been on the books for a while. Probably with visibility based on the current depth of view (though this might be at odds with a proposed desire to be able to drag/drop between assets)

**Comment by TheGameKnave** [comment] 2023-06-30 00:52
Closing as a duplicate of an issue in the app defect tracker

**Closed by TheGameKnave** 2023-06-30 00:52 UTC
Labels: rosterizer
